//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MyFirstWeb.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BankSoap", Namespace="http://tempuri.org/")]
    public partial class Bank : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidVisaDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsExpireDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckVisaFundsOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Bank() {
            this.Url = global::MyFirstWeb.Properties.Settings.Default.MyFirstWeb_localhost_Bank;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidVisaDetailsCompletedEventHandler ValidVisaDetailsCompleted;
        
        /// <remarks/>
        public event IsExpireDateCompletedEventHandler IsExpireDateCompleted;
        
        /// <remarks/>
        public event CheckVisaFundsCompletedEventHandler CheckVisaFundsCompleted;
        
        /// <remarks/>
        public event BuyCompletedEventHandler BuyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidVisaDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidVisaDetails(string id, string VisaNum, string CVV, int month, int year) {
            object[] results = this.Invoke("ValidVisaDetails", new object[] {
                        id,
                        VisaNum,
                        CVV,
                        month,
                        year});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidVisaDetailsAsync(string id, string VisaNum, string CVV, int month, int year) {
            this.ValidVisaDetailsAsync(id, VisaNum, CVV, month, year, null);
        }
        
        /// <remarks/>
        public void ValidVisaDetailsAsync(string id, string VisaNum, string CVV, int month, int year, object userState) {
            if ((this.ValidVisaDetailsOperationCompleted == null)) {
                this.ValidVisaDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidVisaDetailsOperationCompleted);
            }
            this.InvokeAsync("ValidVisaDetails", new object[] {
                        id,
                        VisaNum,
                        CVV,
                        month,
                        year}, this.ValidVisaDetailsOperationCompleted, userState);
        }
        
        private void OnValidVisaDetailsOperationCompleted(object arg) {
            if ((this.ValidVisaDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidVisaDetailsCompleted(this, new ValidVisaDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsExpireDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsExpireDate(int month, int year) {
            object[] results = this.Invoke("IsExpireDate", new object[] {
                        month,
                        year});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsExpireDateAsync(int month, int year) {
            this.IsExpireDateAsync(month, year, null);
        }
        
        /// <remarks/>
        public void IsExpireDateAsync(int month, int year, object userState) {
            if ((this.IsExpireDateOperationCompleted == null)) {
                this.IsExpireDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsExpireDateOperationCompleted);
            }
            this.InvokeAsync("IsExpireDate", new object[] {
                        month,
                        year}, this.IsExpireDateOperationCompleted, userState);
        }
        
        private void OnIsExpireDateOperationCompleted(object arg) {
            if ((this.IsExpireDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsExpireDateCompleted(this, new IsExpireDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckVisaFunds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckVisaFunds(string visanum, int total) {
            object[] results = this.Invoke("CheckVisaFunds", new object[] {
                        visanum,
                        total});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckVisaFundsAsync(string visanum, int total) {
            this.CheckVisaFundsAsync(visanum, total, null);
        }
        
        /// <remarks/>
        public void CheckVisaFundsAsync(string visanum, int total, object userState) {
            if ((this.CheckVisaFundsOperationCompleted == null)) {
                this.CheckVisaFundsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckVisaFundsOperationCompleted);
            }
            this.InvokeAsync("CheckVisaFunds", new object[] {
                        visanum,
                        total}, this.CheckVisaFundsOperationCompleted, userState);
        }
        
        private void OnCheckVisaFundsOperationCompleted(object arg) {
            if ((this.CheckVisaFundsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckVisaFundsCompleted(this, new CheckVisaFundsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Buy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Buy(string visanum, int total) {
            object[] results = this.Invoke("Buy", new object[] {
                        visanum,
                        total});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BuyAsync(string visanum, int total) {
            this.BuyAsync(visanum, total, null);
        }
        
        /// <remarks/>
        public void BuyAsync(string visanum, int total, object userState) {
            if ((this.BuyOperationCompleted == null)) {
                this.BuyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyOperationCompleted);
            }
            this.InvokeAsync("Buy", new object[] {
                        visanum,
                        total}, this.BuyOperationCompleted, userState);
        }
        
        private void OnBuyOperationCompleted(object arg) {
            if ((this.BuyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyCompleted(this, new BuyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ValidVisaDetailsCompletedEventHandler(object sender, ValidVisaDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidVisaDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidVisaDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsExpireDateCompletedEventHandler(object sender, IsExpireDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsExpireDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsExpireDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CheckVisaFundsCompletedEventHandler(object sender, CheckVisaFundsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckVisaFundsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckVisaFundsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void BuyCompletedEventHandler(object sender, BuyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591